import Background from '@/components/background';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import LocalFont from 'next/font/local';
import { ThemeProvider } from '@/components/theme-provider';
import { TailwindIndicator } from '@/components/tailwind-indicator';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OverDocs',
  description: 'Generated by create next app',
};

const calSans = LocalFont({
  src: '../public/fonts/CalSans-SemiBold.ttf',
  variable: '--font-calsans',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${calSans.variable}`}>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
          <Background>{children}</Background>
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
