import Background from '@/components/background';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import LocalFont from 'next/font/local';
const inter = Inter({ subsets: ['latin'] });
import { TailwindIndicator } from '@/components/tailwind-indicator';
export const metadata: Metadata = {
  title: 'Overdocs',
  description: 'Generated by create next app',
};

const calSans = LocalFont({
  src: '../public/fonts/CalSans-SemiBold.ttf',
  variable: '--font-calsans',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${calSans.variable}`}>
        <Background>{children}</Background>
        <TailwindIndicator />
      </body>
    </html>
  );
}
